name: Test GDAL-JVF-DTM wrapper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
          docker pull ghcr.io/osgeo/gdal:ubuntu-full-3.10.3

    - name: Run test
      run: |
          docker run --rm -v ${{ github.workspace }}:/gdal-jvf-dtm-wrapper -w /gdal-jvf-dtm-wrapper \
          ghcr.io/osgeo/gdal:ubuntu-small-3.10.3 \
          python3 -m pip install pytest \
          python3 -m pip install -r requirements.txt \
          python3 -m pytest tests/test_wrapper -v
